apiVersion: apps/v1
kind: Deployment
metadata:
  name: jrny-server-deployment
  labels:
    app: jrny-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jrny-server
  template:
    metadata:
      labels:
        app: jrny-server
    spec:
      containers:
        - name: jrny-server
          image: jrny/server
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128M"
              cpu: "0.5"
          ports:
            - containerPort: 8081

--- 

apiVersion: v1
kind: Service
metadata:
  name: jrny-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8081
    nodePort: 30001
  selector:
    app: jrny-server